// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_A9RzJW2hkwZ4nBevsAaUDFhi7YCVVZY',
    appId: '1:749118014970:web:0e70896c0339caf4c95043',
    messagingSenderId: '749118014970',
    projectId: 'inclusens-app',
    authDomain: 'inclusens-app.firebaseapp.com',
    storageBucket: 'inclusens-app.firebasestorage.app',
    measurementId: 'G-2N0GL2X85B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVNUn2LMa22R24PGi3p5lJGo8dY16EN0E',
    appId: '1:749118014970:android:4602635d958903bec95043',
    messagingSenderId: '749118014970',
    projectId: 'inclusens-app',
    storageBucket: 'inclusens-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZK8xRztQeYyyLWA_Gbp0YVYw-qo14ZKE',
    appId: '1:749118014970:ios:38c549143da5595cc95043',
    messagingSenderId: '749118014970',
    projectId: 'inclusens-app',
    storageBucket: 'inclusens-app.firebasestorage.app',
    iosBundleId: 'com.example.incluesense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZK8xRztQeYyyLWA_Gbp0YVYw-qo14ZKE',
    appId: '1:749118014970:ios:38c549143da5595cc95043',
    messagingSenderId: '749118014970',
    projectId: 'inclusens-app',
    storageBucket: 'inclusens-app.firebasestorage.app',
    iosBundleId: 'com.example.incluesense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_A9RzJW2hkwZ4nBevsAaUDFhi7YCVVZY',
    appId: '1:749118014970:web:02c51522cb59f653c95043',
    messagingSenderId: '749118014970',
    projectId: 'inclusens-app',
    authDomain: 'inclusens-app.firebaseapp.com',
    storageBucket: 'inclusens-app.firebasestorage.app',
    measurementId: 'G-33RB994Y7T',
  );
}
